name: Compilar Mi App
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Constructor
        run: npm install -g nwjs-builder-phoenix

      - name: Ejecutar Compilacion
        run: |
          mkdir build_output
          # Esto empaqueta tu carpeta actual
          npx nwjs-builder-phoenix --tasks win-x64 --out ./build_output .
        
      - name: Subir Resultado Final
        uses: actions/upload-artifact@v4
        with:
          name: MiApp-Ejecutable
          path: ./build_output/
          if-no-files-found: error
